### ISSUE TITLE
PHP Fatal Error in Installer.php

### ISSUE THREAD

**Issue by ryanp2317** [qcubed-4/app-starter#3]
composer create-project qcubed/app-starter my directory here

PHP Fatal error:  Declaration of QCubed\Composer\Installer::uninstall(Composer\Repository\InstalledRepositoryInterface $repo, Composer\Package\PackageInterface $package) must be compatible with Composer\Plugin\PluginInterface::uninstall(Composer\Composer $composer, Composer\IO\IOInterface $io) in my directory here /vendor/qcubed-4/composer/Installer.php on line 143

PHP 7.4.3

**Comment by qcubed-temp** [comment]
Hello! I am an active user of the community https://github.com/qcubed and I am not happy with sleep there. I have copied qcubed v4 to this new repository: https://github.com/qcubed-4. 

Then we could move forward with this excellent framework.

Yes, I have known about this problem since the winter. Because Composer has been updated so much, now Composer 2.0 *. Currently, the composer/composer is not working properly yet. I'm looking for a solution. It seems to me that I have understood Composer 2 and am updating Installer.php and LibraryInstaller.php. I still have a little work to do and testing, I'll let you know when to try.

**Comment by ryanp2317** [comment]
Great! I'm excited by this project.

**Comment by kukrik** [comment]
Hello, @ryanp2317 and @vallter2!
Dear friend @matthiaz, if you have time and interest, you might come here!

<del>
I didn't think that upgrading the composer to the new rules of Composer 2.0 turned out to be quite difficult. And it still takes time to fix.

But I have put a temporary solution here so that it can be used. Try it and let us know. After booting, you must copy the "install" folder from the "project" folder to the corresponding folders. This is a temporary and inconvenient solution!

Also, when deleting the plugin, the corresponding files must be deleted from the "project" folder!

</del>

If you want, you can also explore and test the plugins I created. Comments and observations are welcome!

1) https://github.com/kukrik/ckeditor
2) https://github.com/kukrik/bootstrap-datetimepicker
3) https://github.com/kukrik/toastr
4) https://github.com/kukrik/select2
5) https://github.com/kukrik/counterup2
6) https://github.com/kukrik/bootstrap
<del>
Your help is greatly appreciated in upgrading/redesigning the composer according to the new rules of Composer 2: https://github.com/qcubed-4/composer-test.

Let me know!

EDIT: If necessary, I will give you access to test and update the code!

</del>

**Comment by kukrik** [comment]
Hei @ryanp2317, @vallter2, @matthiaz and other guys...

I got this composer to work beautifully. The updated composer should now comply with Composer 2.0 rules.

It would be great to hear your feedback! To see if the updated composer is working properly!

Good luck!

PS. Please do not try QCubed Unit Tests as this link is still broken. It is currently necessary to upgrade to phpunit version 9.0. It will be a long time ...

**Comment by kukrik** [comment]
Closed! This app-starter works as expected.
