### ISSUE TITLE
qcubed 4 on php 8.x ?

### ISSUE THREAD

**Issue by neuroticimbecile** [qcubed-4/app-starter#5]
Hi All,

Good day!
Are any of you guys still actively using  qcubed 4?
Does it run on php 8.x

It's sad to have to ask this, but:
If you're not using qcubed anymore, which framework did you move on to?

Thank you.

**Comment by kukrik** [comment]
Hi,

I still use the qcubed-4 framework and it works fine for me, but here you have to remember that this framework doesn't work properly since PHP 8.1. I had tested it myself on the php version. This framework works well up to PHP 8.

I cloned from qcubed to qcubed-4 and manage it myself, because there is no sign of life in the community and it was necessary to carry out updates, etc. I also changed composer to 2.0 minimum so that it could continue to work.

If the time is so far that, for example, PHP 8.1 should be switched to, unfortunately, a lot of reworking will have to be done.

**Comment by kukrik** [comment]
Sorry I have one necessary job left to do, it's travis. I also have to rework here, so far I've had fast times and more to come :(:
